=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::AIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AIApi' do
  before do
    # run before each test
    @api_instance = PostBoost::AIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AIApi' do
    it 'should create an instance of AIApi' do
      expect(@api_instance).to be_instance_of(PostBoost::AIApi)
    end
  end

  # unit tests for blog_to_social
  # Generate social media captions from a blog post
  # Generates platform-specific social media captions from a blog post URL or directly provided title and excerpt. Each platform generates one caption, which consumes one AI credit from the workspace&#39;s monthly allowance.  **Input modes** (at least one required): - **URL mode**: provide &#x60;url&#x60; and the API scrapes the blog content automatically, including detecting the featured image via &#x60;og:image&#x60;. - **Direct mode**: provide &#x60;title&#x60; and &#x60;excerpt&#x60; directly (no scraping).  If both are provided, direct values take priority.  When &#x60;create_post&#x60; is &#x60;true&#x60;, a draft post is created in the workspace with per-account caption versions. If an image is available (from &#x60;image_url&#x60; or the scraped &#x60;og:image&#x60;), it is imported into the workspace media library and attached to the draft post. 
  # @param workspace_uuid UUID of the workspace.
  # @param blog_to_social_input 
  # @param [Hash] opts the optional parameters
  # @return [BlogToSocial200Response]
  describe 'blog_to_social test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
