=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::AIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AIApi' do
  before do
    # run before each test
    @api_instance = PostBoost::AIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AIApi' do
    it 'should create an instance of AIApi' do
      expect(@api_instance).to be_instance_of(PostBoost::AIApi)
    end
  end

  # unit tests for blog_to_social
  # Generate social media captions from a blog post
  # Generates platform-specific social media captions from a blog post URL or directly provided title and excerpt. Each platform generates one caption, which consumes one AI credit from the workspace&#39;s monthly allowance.  **Input modes** (at least one required): - **URL mode**: provide &#x60;url&#x60; and the API scrapes the blog content automatically, including detecting the featured image via &#x60;og:image&#x60;. - **Direct mode**: provide &#x60;title&#x60; and &#x60;excerpt&#x60; directly (no scraping).  If both are provided, direct values take priority.  When &#x60;create_post&#x60; is &#x60;true&#x60;, a draft post is created in the workspace with per-account caption versions. If an image is available (from &#x60;image_url&#x60; or the scraped &#x60;og:image&#x60;), it is imported into the workspace media library and attached to the draft post. 
  # @param workspace_uuid UUID of the workspace.
  # @param blog_to_social_input 
  # @param [Hash] opts the optional parameters
  # @return [BlogToSocial200Response]
  describe 'blog_to_social test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for image_alt_text
  # Generate alt text for a media image using AI
  # Analyzes an existing workspace media item and generates accessible alt text. The alt text is saved back to the media record. Costs 1 AI credit per call. 
  # @param workspace_uuid UUID of the workspace.
  # @param image_alt_text_input 
  # @param [Hash] opts the optional parameters
  # @return [ImageAltText200Response]
  describe 'image_alt_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for image_edit
  # Edit an existing media image using AI
  # Edits an existing workspace media item using the source image and a text prompt. Optionally accepts a mask (transparent areas are replaced). Saves results to the media library. Credits: &#x60;count × credit_weight&#x60;. 
  # @param workspace_uuid UUID of the workspace.
  # @param image_edit_input 
  # @param [Hash] opts the optional parameters
  # @return [ImageGenerate200Response]
  describe 'image_edit test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for image_generate
  # Generate social media images from a caption
  # Generates one or more images and saves them immediately to the workspace media library.  **Standard mode** (recommended): provide &#x60;caption&#x60; + &#x60;platform&#x60;. PostBoost builds a professional image prompt internally using platform-specific templates. No prompt engineering required.  **Developer mode**: provide &#x60;prompt&#x60; directly to bypass prompt building. If both &#x60;caption&#x60; and &#x60;prompt&#x60; are sent, standard mode runs.  Credits: &#x60;count x credit_weight&#x60; (default: 5 per image). 
  # @param workspace_uuid UUID of the workspace.
  # @param image_generate_input 
  # @param [Hash] opts the optional parameters
  # @return [ImageGenerate200Response]
  describe 'image_generate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for image_prompt
  # Build an optimized image prompt from a social media caption
  # Builds a professional image generation prompt from a caption and platform. No image is generated. Use this to preview the prompt before calling &#x60;image-generate&#x60;. Costs 1 AI credit per call.  When &#x60;image-generate&#x60; builds the prompt internally (standard mode), no credit is charged for the prompt step. 
  # @param workspace_uuid UUID of the workspace.
  # @param image_prompt_input 
  # @param [Hash] opts the optional parameters
  # @return [ImagePrompt200Response]
  describe 'image_prompt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for image_variations
  # Generate variations of an existing media image
  # Creates one or more variations of an existing workspace media item. Saves results to the media library. Credits: &#x60;count × credit_weight&#x60;. 
  # @param workspace_uuid UUID of the workspace.
  # @param image_variations_input 
  # @param [Hash] opts the optional parameters
  # @return [ImageVariations200Response]
  describe 'image_variations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
