=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::MediaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MediaApi' do
  before do
    # run before each test
    @api_instance = PostBoost::MediaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MediaApi' do
    it 'should create an instance of MediaApi' do
      expect(@api_instance).to be_instance_of(PostBoost::MediaApi)
    end
  end

  # unit tests for abort_chunked_upload
  # Abort chunked upload
  # Cancel an in-progress chunked upload session and clean up uploaded chunks.
  # @param workspace_uuid UUID of the workspace.
  # @param upload_uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'abort_chunked_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for complete_chunked_upload
  # Complete chunked upload
  # Signal that all chunks have been uploaded. Returns the final media object.
  # @param workspace_uuid UUID of the workspace.
  # @param upload_uuid 
  # @param [Hash] opts the optional parameters
  # @return [Media]
  describe 'complete_chunked_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_media_bulk
  # Delete media (bulk)
  # Delete one or more media items by their IDs.
  # @param workspace_uuid UUID of the workspace.
  # @param delete_media_bulk_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_media_bulk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_media
  # Get media
  # Returns a single media asset.
  # @param workspace_uuid UUID of the workspace.
  # @param media_uuid UUID of the media asset.
  # @param [Hash] opts the optional parameters
  # @return [Media]
  describe 'get_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_remote_upload_status
  # Get remote upload status
  # Poll the status of an in-progress remote media download.
  # @param workspace_uuid UUID of the workspace.
  # @param download_id 
  # @param [Hash] opts the optional parameters
  # @return [GetRemoteUploadStatus200Response]
  describe 'get_remote_upload_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for initiate_chunked_upload
  # Initiate chunked upload
  # Start a chunked upload session for large files. Returns an &#x60;upload_uuid&#x60;, &#x60;chunk_size&#x60;, and &#x60;total_chunks&#x60; to use for subsequent chunk requests. 
  # @param workspace_uuid UUID of the workspace.
  # @param initiate_chunked_upload_request 
  # @param [Hash] opts the optional parameters
  # @return [InitiateChunkedUpload200Response]
  describe 'initiate_chunked_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for initiate_remote_upload
  # Initiate remote upload
  # Download a file from a remote URL into the media library. For small files the media object is returned immediately. For large files a &#x60;download_id&#x60; is returned — poll the status endpoint. 
  # @param workspace_uuid UUID of the workspace.
  # @param initiate_remote_upload_request 
  # @param [Hash] opts the optional parameters
  # @return [InitiateRemoteUpload200Response]
  describe 'initiate_remote_upload test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_media
  # List media
  # Returns a paginated list of media assets in the workspace library.
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (20 items per page).
  # @return [ListMedia200Response]
  describe 'list_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_media
  # Update media
  # Update the alt text of a media asset.
  # @param workspace_uuid UUID of the workspace.
  # @param media_uuid UUID of the media asset.
  # @param update_media_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_chunk
  # Upload a chunk
  # Upload a single chunk of a chunked upload session.
  # @param workspace_uuid UUID of the workspace.
  # @param upload_uuid 
  # @param chunk 
  # @param chunk_index Zero-based index of this chunk.
  # @param [Hash] opts the optional parameters
  # @return [UploadChunk200Response]
  describe 'upload_chunk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_media
  # Upload media (binary)
  # Upload a file directly as multipart form data.
  # @param workspace_uuid UUID of the workspace.
  # @param file The file to upload.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :alt_text Alternative text for accessibility.
  # @return [Media]
  describe 'upload_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
