=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::PostsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PostsApi' do
  before do
    # run before each test
    @api_instance = PostBoost::PostsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostsApi' do
    it 'should create an instance of PostsApi' do
      expect(@api_instance).to be_instance_of(PostBoost::PostsApi)
    end
  end

  # unit tests for add_post_to_queue
  # Add post to queue
  # Add an existing post to the smart publishing queue.
  # @param workspace_uuid UUID of the workspace.
  # @param post_uuid UUID of the post.
  # @param [Hash] opts the optional parameters
  # @return [ScheduleResult]
  describe 'add_post_to_queue test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for approve_post
  # Approve post
  # Approve a post that is pending review.
  # @param workspace_uuid UUID of the workspace.
  # @param post_uuid UUID of the post.
  # @param [Hash] opts the optional parameters
  # @return [ScheduleResult]
  describe 'approve_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_post
  # Create post
  # Create a new post. Use &#x60;schedule: true&#x60; with &#x60;date&#x60; and &#x60;time&#x60; to schedule, &#x60;schedule_now: true&#x60; to publish immediately, or &#x60;queue: true&#x60; to add to the smart publishing queue. 
  # @param workspace_uuid UUID of the workspace.
  # @param post_input 
  # @param [Hash] opts the optional parameters
  # @return [Post]
  describe 'create_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_post
  # Delete post
  # @param workspace_uuid UUID of the workspace.
  # @param post_uuid UUID of the post.
  # @param [Hash] opts the optional parameters
  # @option opts [DeletePostRequest] :delete_post_request 
  # @return [DeleteResult]
  describe 'delete_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_posts_bulk
  # Delete posts (bulk)
  # Delete multiple posts at once.
  # @param workspace_uuid UUID of the workspace.
  # @param delete_posts_bulk_request 
  # @param [Hash] opts the optional parameters
  # @return [DeleteResult]
  describe 'delete_posts_bulk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_post
  # Get post
  # @param workspace_uuid UUID of the workspace.
  # @param post_uuid UUID of the post.
  # @param [Hash] opts the optional parameters
  # @return [Post]
  describe 'get_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_posts
  # List posts
  # Returns a paginated list of posts in the workspace.
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @return [ListPosts200Response]
  describe 'list_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for schedule_post
  # Schedule post
  # Schedule an existing post. Set &#x60;postNow: true&#x60; to publish immediately.
  # @param workspace_uuid UUID of the workspace.
  # @param post_uuid UUID of the post.
  # @param schedule_post_request 
  # @param [Hash] opts the optional parameters
  # @return [ScheduleResult]
  describe 'schedule_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_post
  # Update post
  # @param workspace_uuid UUID of the workspace.
  # @param post_uuid UUID of the post.
  # @param post_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
