=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::ReceiptsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReceiptsApi' do
  before do
    # run before each test
    @api_instance = PostBoost::ReceiptsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReceiptsApi' do
    it 'should create an instance of ReceiptsApi' do
      expect(@api_instance).to be_instance_of(PostBoost::ReceiptsApi)
    end
  end

  # unit tests for create_receipt
  # Create receipt
  # Creates a billing receipt record for a workspace. Admin only.
  # @param receipt_input 
  # @param [Hash] opts the optional parameters
  # @return [Receipt]
  describe 'create_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_receipt
  # Delete receipt
  # Permanently deletes a single receipt. Admin only.
  # @param receipt_uuid UUID of the receipt.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_receipts_bulk
  # Delete receipts (bulk)
  # Permanently deletes one or more receipt records. Admin only.
  # @param delete_receipts_bulk_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_receipts_bulk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_receipt
  # Get receipt
  # Returns a single receipt by UUID. Admin only.
  # @param receipt_uuid UUID of the receipt.
  # @param [Hash] opts the optional parameters
  # @return [Receipt]
  describe 'get_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_receipts
  # List receipts
  # Returns a paginated list of billing receipts. Filter by workspace UUID or invoice number. Admin only.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :workspace_uuid 
  # @option opts [String] :invoice_number 
  # @option opts [Integer] :page Page number (15 items per page).
  # @return [ListReceipts200Response]
  describe 'list_receipts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_receipt
  # Update receipt
  # Updates a receipt&#39;s transaction details, amount, or payment date. Admin only.
  # @param receipt_uuid UUID of the receipt.
  # @param receipt_update_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
