=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::SubscriptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SubscriptionsApi' do
  before do
    # run before each test
    @api_instance = PostBoost::SubscriptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SubscriptionsApi' do
    it 'should create an instance of SubscriptionsApi' do
      expect(@api_instance).to be_instance_of(PostBoost::SubscriptionsApi)
    end
  end

  # unit tests for add_generic_subscription
  # Add generic subscription
  # @param workspace_uuid UUID of the workspace.
  # @param add_generic_subscription_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'add_generic_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cancel_subscription
  # Cancel subscription
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cancel_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for change_subscription_plan
  # Change subscription plan
  # @param workspace_uuid UUID of the workspace.
  # @param change_subscription_plan_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'change_subscription_plan test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for checkout_subscription
  # New subscription checkout
  # Returns a Stripe Checkout URL for a new subscription.
  # @param workspace_uuid UUID of the workspace.
  # @param checkout_subscription_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSubscription200Response]
  describe 'checkout_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_subscription
  # Create subscription
  # @param workspace_uuid UUID of the workspace.
  # @param subscription_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'create_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_subscription
  # Delete subscription
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_subscription
  # Get subscription
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Subscription]
  describe 'get_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_generic_subscription
  # Remove generic subscription
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'remove_generic_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for resume_subscription
  # Resume subscription
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'resume_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_subscription
  # Update subscription
  # @param workspace_uuid UUID of the workspace.
  # @param subscription_update_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
