=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::TagsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TagsApi' do
  before do
    # run before each test
    @api_instance = PostBoost::TagsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TagsApi' do
    it 'should create an instance of TagsApi' do
      expect(@api_instance).to be_instance_of(PostBoost::TagsApi)
    end
  end

  # unit tests for create_tag
  # Create tag
  # @param workspace_uuid UUID of the workspace.
  # @param tag_input 
  # @param [Hash] opts the optional parameters
  # @return [Tag]
  describe 'create_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_tag
  # Delete tag
  # @param workspace_uuid UUID of the workspace.
  # @param tag_uuid UUID of the tag.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_tag
  # Get tag
  # @param workspace_uuid UUID of the workspace.
  # @param tag_uuid UUID of the tag.
  # @param [Hash] opts the optional parameters
  # @return [Tag]
  describe 'get_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_tags
  # List tags
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [ListTags200Response]
  describe 'list_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_tag
  # Update tag
  # @param workspace_uuid UUID of the workspace.
  # @param tag_uuid UUID of the tag.
  # @param tag_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
