=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PostBoost::WorkspacesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkspacesApi' do
  before do
    # run before each test
    @api_instance = PostBoost::WorkspacesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkspacesApi' do
    it 'should create an instance of WorkspacesApi' do
      expect(@api_instance).to be_instance_of(PostBoost::WorkspacesApi)
    end
  end

  # unit tests for add_user_to_workspace
  # Add user to workspace
  # @param workspace_uuid UUID of the workspace.
  # @param workspace_user_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'add_user_to_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_workspace
  # Create workspace
  # Create a new workspace. Admin only.
  # @param workspace_input 
  # @param [Hash] opts the optional parameters
  # @return [Workspace]
  describe 'create_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_workspace
  # Delete workspace
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_workspaces_bulk
  # Delete workspaces (bulk)
  # @param delete_workspaces_bulk_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_workspaces_bulk test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_workspace
  # Get workspace
  # @param workspace_uuid UUID of the workspace.
  # @param [Hash] opts the optional parameters
  # @return [Workspace]
  describe 'get_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_workspaces
  # List workspaces
  # Returns a paginated list of all workspaces. Admin only.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :keyword 
  # @option opts [String] :subscription_status 
  # @option opts [String] :access_status 
  # @return [ListWorkspaces200Response]
  describe 'list_workspaces test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_user_from_workspace
  # Remove user from workspace
  # @param workspace_uuid UUID of the workspace.
  # @param remove_user_from_workspace_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'remove_user_from_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_workspace
  # Update workspace
  # @param workspace_uuid UUID of the workspace.
  # @param workspace_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_workspace_user
  # Update user role in workspace
  # @param workspace_uuid UUID of the workspace.
  # @param workspace_user_input 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_workspace_user test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
