=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

# Common files
require 'postboost/api_client'
require 'postboost/api_error'
require 'postboost/version'
require 'postboost/configuration'

# Models
require 'postboost/models/account'
require 'postboost/models/add_generic_subscription_request'
require 'postboost/models/blog_to_social200_response'
require 'postboost/models/blog_to_social429_response'
require 'postboost/models/blog_to_social_caption'
require 'postboost/models/blog_to_social_input'
require 'postboost/models/blog_to_social_media'
require 'postboost/models/blog_to_social_response'
require 'postboost/models/change_subscription_plan_request'
require 'postboost/models/checkout_subscription200_response'
require 'postboost/models/checkout_subscription_request'
require 'postboost/models/delete_media_bulk_request'
require 'postboost/models/delete_mode'
require 'postboost/models/delete_post_request'
require 'postboost/models/delete_posts_bulk_request'
require 'postboost/models/delete_receipts_bulk_request'
require 'postboost/models/delete_result'
require 'postboost/models/delete_user400_response'
require 'postboost/models/delete_users_bulk_request'
require 'postboost/models/delete_workspaces_bulk_request'
require 'postboost/models/generated_image_item'
require 'postboost/models/get_remote_upload_status200_response'
require 'postboost/models/image_alt_text200_response'
require 'postboost/models/image_alt_text_input'
require 'postboost/models/image_alt_text_response'
require 'postboost/models/image_edit_input'
require 'postboost/models/image_generate200_response'
require 'postboost/models/image_generate429_response'
require 'postboost/models/image_generate_input'
require 'postboost/models/image_generation_response'
require 'postboost/models/image_prompt200_response'
require 'postboost/models/image_prompt429_response'
require 'postboost/models/image_prompt_input'
require 'postboost/models/image_prompt_response'
require 'postboost/models/image_variations200_response'
require 'postboost/models/image_variations_input'
require 'postboost/models/image_variations_response'
require 'postboost/models/initiate_chunked_upload201_response'
require 'postboost/models/initiate_chunked_upload_request'
require 'postboost/models/initiate_remote_upload201_response'
require 'postboost/models/initiate_remote_upload201_response_one_of'
require 'postboost/models/initiate_remote_upload_request'
require 'postboost/models/list_accounts200_response'
require 'postboost/models/list_media200_response'
require 'postboost/models/list_posts200_response'
require 'postboost/models/list_receipts200_response'
require 'postboost/models/list_tags200_response'
require 'postboost/models/list_users200_response'
require 'postboost/models/list_workspaces200_response'
require 'postboost/models/media'
require 'postboost/models/pagination_meta'
require 'postboost/models/pagination_meta_links'
require 'postboost/models/pagination_meta_meta'
require 'postboost/models/post'
require 'postboost/models/post_content'
require 'postboost/models/post_input'
require 'postboost/models/post_status'
require 'postboost/models/post_version'
require 'postboost/models/receipt'
require 'postboost/models/receipt_input'
require 'postboost/models/receipt_update_input'
require 'postboost/models/remove_user_from_workspace_request'
require 'postboost/models/schedule_post_request'
require 'postboost/models/schedule_result'
require 'postboost/models/subscription'
require 'postboost/models/subscription_input'
require 'postboost/models/subscription_status'
require 'postboost/models/subscription_update_input'
require 'postboost/models/tag'
require 'postboost/models/tag_input'
require 'postboost/models/update_media_request'
require 'postboost/models/upload_chunk201_response'
require 'postboost/models/user'
require 'postboost/models/user_input'
require 'postboost/models/user_update_input'
require 'postboost/models/workspace'
require 'postboost/models/workspace_input'
require 'postboost/models/workspace_user_input'

# APIs
require 'postboost/api/ai_api'
require 'postboost/api/accounts_api'
require 'postboost/api/media_api'
require 'postboost/api/posts_api'
require 'postboost/api/receipts_api'
require 'postboost/api/subscriptions_api'
require 'postboost/api/tags_api'
require 'postboost/api/users_api'
require 'postboost/api/workspaces_api'

module PostBoost
  class << self
    # Customize default settings for the SDK using block.
    #   PostBoost.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
