=begin
#PostBoost API

#The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

The version of the OpenAPI document: 1.0.0
Contact: hi@postboost.co
Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module PostBoost
  # At least one of `url` or (`title` + `excerpt`) must be provided. If both are given, direct values take priority over the scraped URL content. 
  class BlogToSocialInput
    # Blog post URL to scrape. Required if `title` and `excerpt` are not provided.
    attr_accessor :url

    # Blog post title. Required if `url` is not provided.
    attr_accessor :title

    # Blog post summary or excerpt. Required if `url` is not provided.
    attr_accessor :excerpt

    # Featured image URL for the blog post. When `create_post` is `true`, the image is imported into the workspace media library and attached to the draft post. If omitted in URL mode, the scraper attempts to extract the `og:image` meta tag. 
    attr_accessor :image_url

    # Target social media platforms. Only connected accounts matching these platforms are used. If omitted, all connected accounts in the workspace are targeted. 
    attr_accessor :platforms

    # Specific account IDs to generate captions for. Takes precedence over `platforms` when both are provided. 
    attr_accessor :account_ids

    # Writing tone for all generated captions.
    attr_accessor :tone

    # Desired length of the generated captions.
    attr_accessor :content_length

    # Hashtag quantity: none (0), few (1-3), some (3-5), many (5+).
    attr_accessor :hashtags

    # Call-to-action type appended to each caption.
    attr_accessor :cta

    # Output language as an ISO 639-1 code (e.g. `en`, `de`, `fr`). Use `auto` to match the blog post's language automatically. 
    attr_accessor :language

    # Additional instructions appended to the AI prompt (e.g. \"always mention our free tier\").
    attr_accessor :custom_instructions

    # When `true`, creates a draft post in the workspace with per-account caption versions. If an image is available, it is imported and attached to the post. 
    attr_accessor :create_post

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'url' => :'url',
        :'title' => :'title',
        :'excerpt' => :'excerpt',
        :'image_url' => :'image_url',
        :'platforms' => :'platforms',
        :'account_ids' => :'account_ids',
        :'tone' => :'tone',
        :'content_length' => :'content_length',
        :'hashtags' => :'hashtags',
        :'cta' => :'cta',
        :'language' => :'language',
        :'custom_instructions' => :'custom_instructions',
        :'create_post' => :'create_post'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'url' => :'String',
        :'title' => :'String',
        :'excerpt' => :'String',
        :'image_url' => :'String',
        :'platforms' => :'Array<String>',
        :'account_ids' => :'Array<Integer>',
        :'tone' => :'String',
        :'content_length' => :'String',
        :'hashtags' => :'String',
        :'cta' => :'String',
        :'language' => :'String',
        :'custom_instructions' => :'String',
        :'create_post' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PostBoost::BlogToSocialInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PostBoost::BlogToSocialInput`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'excerpt')
        self.excerpt = attributes[:'excerpt']
      end

      if attributes.key?(:'image_url')
        self.image_url = attributes[:'image_url']
      end

      if attributes.key?(:'platforms')
        if (value = attributes[:'platforms']).is_a?(Array)
          self.platforms = value
        end
      end

      if attributes.key?(:'account_ids')
        if (value = attributes[:'account_ids']).is_a?(Array)
          self.account_ids = value
        end
      end

      if attributes.key?(:'tone')
        self.tone = attributes[:'tone']
      else
        self.tone = 'engaging'
      end

      if attributes.key?(:'content_length')
        self.content_length = attributes[:'content_length']
      else
        self.content_length = 'medium'
      end

      if attributes.key?(:'hashtags')
        self.hashtags = attributes[:'hashtags']
      else
        self.hashtags = 'few'
      end

      if attributes.key?(:'cta')
        self.cta = attributes[:'cta']
      else
        self.cta = 'none'
      end

      if attributes.key?(:'language')
        self.language = attributes[:'language']
      else
        self.language = 'auto'
      end

      if attributes.key?(:'custom_instructions')
        self.custom_instructions = attributes[:'custom_instructions']
      end

      if attributes.key?(:'create_post')
        self.create_post = attributes[:'create_post']
      else
        self.create_post = false
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@url.nil? && @url.to_s.length > 2000
        invalid_properties.push('invalid value for "url", the character length must be smaller than or equal to 2000.')
      end

      if !@title.nil? && @title.to_s.length > 500
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 500.')
      end

      if !@excerpt.nil? && @excerpt.to_s.length > 5000
        invalid_properties.push('invalid value for "excerpt", the character length must be smaller than or equal to 5000.')
      end

      if !@image_url.nil? && @image_url.to_s.length > 2000
        invalid_properties.push('invalid value for "image_url", the character length must be smaller than or equal to 2000.')
      end

      if !@language.nil? && @language.to_s.length > 10
        invalid_properties.push('invalid value for "language", the character length must be smaller than or equal to 10.')
      end

      if !@custom_instructions.nil? && @custom_instructions.to_s.length > 500
        invalid_properties.push('invalid value for "custom_instructions", the character length must be smaller than or equal to 500.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@url.nil? && @url.to_s.length > 2000
      return false if !@title.nil? && @title.to_s.length > 500
      return false if !@excerpt.nil? && @excerpt.to_s.length > 5000
      return false if !@image_url.nil? && @image_url.to_s.length > 2000
      tone_validator = EnumAttributeValidator.new('String', ["neutral", "friendly", "formal", "edgy", "engaging", "casual", "professional", "humorous", "inspirational", "conversational"])
      return false unless tone_validator.valid?(@tone)
      content_length_validator = EnumAttributeValidator.new('String', ["short", "medium", "long"])
      return false unless content_length_validator.valid?(@content_length)
      hashtags_validator = EnumAttributeValidator.new('String', ["none", "few", "some", "many"])
      return false unless hashtags_validator.valid?(@hashtags)
      cta_validator = EnumAttributeValidator.new('String', ["none", "question", "link", "subscribe", "follow", "share", "learn_more", "signup", "buy", "download"])
      return false unless cta_validator.valid?(@cta)
      return false if !@language.nil? && @language.to_s.length > 10
      return false if !@custom_instructions.nil? && @custom_instructions.to_s.length > 500
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      if url.to_s.length > 2000
        fail ArgumentError, 'invalid value for "url", the character length must be smaller than or equal to 2000.'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      if title.to_s.length > 500
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 500.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] excerpt Value to be assigned
    def excerpt=(excerpt)
      if excerpt.nil?
        fail ArgumentError, 'excerpt cannot be nil'
      end

      if excerpt.to_s.length > 5000
        fail ArgumentError, 'invalid value for "excerpt", the character length must be smaller than or equal to 5000.'
      end

      @excerpt = excerpt
    end

    # Custom attribute writer method with validation
    # @param [Object] image_url Value to be assigned
    def image_url=(image_url)
      if image_url.nil?
        fail ArgumentError, 'image_url cannot be nil'
      end

      if image_url.to_s.length > 2000
        fail ArgumentError, 'invalid value for "image_url", the character length must be smaller than or equal to 2000.'
      end

      @image_url = image_url
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tone Object to be assigned
    def tone=(tone)
      validator = EnumAttributeValidator.new('String', ["neutral", "friendly", "formal", "edgy", "engaging", "casual", "professional", "humorous", "inspirational", "conversational"])
      unless validator.valid?(tone)
        fail ArgumentError, "invalid value for \"tone\", must be one of #{validator.allowable_values}."
      end
      @tone = tone
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] content_length Object to be assigned
    def content_length=(content_length)
      validator = EnumAttributeValidator.new('String', ["short", "medium", "long"])
      unless validator.valid?(content_length)
        fail ArgumentError, "invalid value for \"content_length\", must be one of #{validator.allowable_values}."
      end
      @content_length = content_length
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] hashtags Object to be assigned
    def hashtags=(hashtags)
      validator = EnumAttributeValidator.new('String', ["none", "few", "some", "many"])
      unless validator.valid?(hashtags)
        fail ArgumentError, "invalid value for \"hashtags\", must be one of #{validator.allowable_values}."
      end
      @hashtags = hashtags
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cta Object to be assigned
    def cta=(cta)
      validator = EnumAttributeValidator.new('String', ["none", "question", "link", "subscribe", "follow", "share", "learn_more", "signup", "buy", "download"])
      unless validator.valid?(cta)
        fail ArgumentError, "invalid value for \"cta\", must be one of #{validator.allowable_values}."
      end
      @cta = cta
    end

    # Custom attribute writer method with validation
    # @param [Object] language Value to be assigned
    def language=(language)
      if language.nil?
        fail ArgumentError, 'language cannot be nil'
      end

      if language.to_s.length > 10
        fail ArgumentError, 'invalid value for "language", the character length must be smaller than or equal to 10.'
      end

      @language = language
    end

    # Custom attribute writer method with validation
    # @param [Object] custom_instructions Value to be assigned
    def custom_instructions=(custom_instructions)
      if custom_instructions.nil?
        fail ArgumentError, 'custom_instructions cannot be nil'
      end

      if custom_instructions.to_s.length > 500
        fail ArgumentError, 'invalid value for "custom_instructions", the character length must be smaller than or equal to 500.'
      end

      @custom_instructions = custom_instructions
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          url == o.url &&
          title == o.title &&
          excerpt == o.excerpt &&
          image_url == o.image_url &&
          platforms == o.platforms &&
          account_ids == o.account_ids &&
          tone == o.tone &&
          content_length == o.content_length &&
          hashtags == o.hashtags &&
          cta == o.cta &&
          language == o.language &&
          custom_instructions == o.custom_instructions &&
          create_post == o.create_post
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [url, title, excerpt, image_url, platforms, account_ids, tone, content_length, hashtags, cta, language, custom_instructions, create_post].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = PostBoost.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
